version: "3.5"

services:
  mosquitto:
    image: eclipse-mosquitto
    deploy:
      replicas: 1
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf
    networks:
      mqtt:
        aliases:
          - mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
    deploy:
      placement:
        constraints:
          - 'node.hostname == noether'

configs:
  mosquitto_config:
    name: mosquitto_config-${EPOCH}
    file: conf/mosquitto.conf

networks:
  mqtt:
    internal: true
  bridge:
    external: true
