---
version: '3.5'

# Based on https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/docker-compose.yml
# Changed to cluster all elements of the stack for N=3 redundancy

services:

  vmstorage-1:
    image: victoriametrics/vmstorage
    volumes:
      - strgdata:/storage
    command:
      - '--storageDataPath=/storage'
      - '--retentionPeriod=9999y'
    networks:
      - vminsert
    deploy:
      placement:
        constraints:
          - node.Hostname==boxer
    restart: always

  vmstorage-2:
    image: victoriametrics/vmstorage
    volumes:
      - strgdata:/storage
    command:
      - '--storageDataPath=/storage'
      - '--retentionPeriod=9999y'
    networks:
      - vminsert
    deploy:
      placement:
        constraints:
          - node.Hostname==gauss
    restart: always

  vmstorage-3:
    image: victoriametrics/vmstorage
    volumes:
      - strgdata:/storage
    command:
      - '--storageDataPath=/storage'
      - '--retentionPeriod=9999y'
    networks:
      - vminsert
    deploy:
      placement:
        constraints:
          - node.Hostname==k0node1
    restart: always

  vminsert:
    image: victoriametrics/vminsert
    depends_on:
      - vmstorage-1
      - vmstorage-2
      - vmstorage-3
    command:
      - '--replicationFactor=2'
      - '--storageNode=vmstorage-1:8400'
      - '--storageNode=vmstorage-2:8400'
      - '--storageNode=vmstorage-3:8400'
      - '-influxSkipSingleField'
    networks:
      - vminsert
    ports:
      - 8480:8480
    restart: always

  vmselect:
    image: victoriametrics/vmselect
    depends_on:
      - vmstorage-1
      - vmstorage-2
      - vmstorage-3
    command:
      - '--replicationFactor=2'
      - '--storageNode=vmstorage-1:8401'
      - '--storageNode=vmstorage-2:8401'
      - '--storageNode=vmstorage-3:8401'
      - '-dedup.minScrapeInterval=1ms'
    networks:
      - vminsert
      - vmselect
    ports:
      - 8481:8481
    restart: always

  vmagent:
    image: victoriametrics/vmagent
    depends_on:
      - vminsert
      - vmselect
    networks:
      - vminsert
      - vmselect
      - bridge
    volumes:
      - vmagentdata:/vmagentdata
    configs:
      - source: vmagent_prometheus
        target: /etc/prometheus/prometheus.yml
      - source: victoriametrics_scrape_config
        target: /etc/prometheus.d/victoriametrics.yml
      - source: infra_scrape_config
        target: /etc/prometheus.d/infra.yml
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--remoteWrite.url=http://vminsert:8480/insert/0/prometheus/'
    restart: always

  vmalert:
    image: victoriametrics/vmalert
    depends_on:
      - vmselect
      - vminsert
    networks:
      - vmselect
      - vminsert
    configs:
      - source: vmalert_alerts
        target: /etc/alerts/alerts.yml
    command:
      - '--datasource.url=http://vmselect:8481/select/0/prometheus'
      - '--remoteRead.url=http://vmselect:8481/select/0/prometheus'
      - '--remoteWrite.url=http://vminsert:8480/insert/0/prometheus'
      - '--notifier.url=http://alertmanager:9093/'
      - '--rule=/etc/alerts/*.yml'
      # display source of alerts in grafana
      - '-external.url=http://victoriametrics.shill.gq:3000' #grafana outside container
      # when copypaste the line below be aware of '$$' for escaping in '$expr'
      - '--external.alert.source=explore?orgId=1&left=["now-1h","now","VictoriaMetrics",{"expr":"{{$$expr|quotesEscape|crlfEscape|queryEscape}}"},{"mode":"Metrics"},{"ui":[true,true,true,"none"]}]'
    restart: always

  alertmanager:
    image:  prom/alertmanager
    configs:
      - source: alertmanager
        target: /config/alertmanager.yml
    command:
      - '--config.file=/config/alertmanager.yml'
    ports:
      - 9093:9093
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - vmselect
    networks:
      - vmselect
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasource.yml
      - source: grafana_vm_dashboard
        target: /var/lib/grafana/dashboards/vm.json
      - source: grafana_vmagent_dashboard
        target: /var/lib/grafana/dashboards/vmagent.json
      - source: grafana_vmalert_dashboard
        target: /var/lib/grafana/dashboards/vmalert.json
    deploy:
      placement:
        constraints:
          - node.Hostname==boxer
    restart: always

configs:
  vmagent_prometheus:
    file: ./vmagent-prometheus.yml
  victoriametrics_scrape_config:
    file: ./victoriametrics_scrape_config.yml
  infra_scrape_config:
    external: true
  grafana_datasources:
    file: ./grafana/datasource.yml
  grafana_vm_dashboard:
    file: dashboards/victoriametrics.json
  grafana_vmagent_dashboard:
    file: dashboards/vmagent.json
  grafana_vmalert_dashboard:
    file: dashboards/vmalert.json
  vmalert_alerts:
    file: alerts.yml
  alertmanager:
    file: alertmanager.yml

volumes:
  strgdata:
  grafanadata:
  vmagentdata:

networks:
  vminsert:
    internal: true
  vmselect:
    internal: true
  bridge:
    external: true

