version: "3.5"

services:
  mosquitto:
    image: eclipse-mosquitto
    deploy:
      replicas: 1
    volumes:
      - /var/lib/syncthing/Sync/swarm/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883

