---
version: '3.5'

services:
  power-meter:
    image: enkiusz/power-meter
    container_name: power-meter
    network_mode: bridge
    restart: always

    devices:
      - /dev/ttyACM0

    environment:
      PYSERIAL_DEVICE: SER=649383232313513101F1
      BROKER_URL: mqtt://mqtt
      MQTT_TOPIC: house_loads
      QUANTUM: 2.5
